### ISSUE TITLE
boidcmd setup TypeError: Cannot read property "length" of undefined

### ISSUE THREAD

**Issue by giosal** [Boid-John/boidcmd#14]
Hi,

After successfully completing all the previous steps, I'm getting the following error when launching boidcmd setup:

```
waiting for project information
⠧ /home/nnn/.nvm/versions/node/v14.2.0/lib/node_modules/boidcmd/node_modules/sax/lib/sax.js:959
    if (i < chunk.length) {
                  ^

TypeError: Cannot read property 'length' of undefined
    at charAt (/home/nnn/.nvm/versions/node/v14.2.0/lib/node_modules/boidcmd/node_modules/sax/lib/sax.js:959:19)
    at SAXParser.write (/home/nnn/.nvm/versions/node/v14.2.0/lib/node_modules/boidcmd/node_modules/sax/lib/sax.js:983:11)
    at module.exports (/home/nnn/.nvm/versions/node/v14.2.0/lib/node_modules/boidcmd/node_modules/xml-js/lib/xml2js.js:346:12)
    at Object.module.exports [as xml2json] (/home/nnn/.nvm/versions/node/v14.2.0/lib/node_modules/boidcmd/node_modules/xml-js/lib/xml2json.js:13:8)
    at ReadFileContext.callback (/home/nnn/.nvm/versions/node/v14.2.0/lib/node_modules/boidcmd/index.js:465:31)
    at FSReqCallback.readFileAfterOpen [as oncomplete] (fs.js:260:13)
```

CentOS 7

**Comment by ghobson2013** [comment]
Hi,

The node version in centos7 isnt supported, we tested it works only on Debian/Ubuntu.
boidcmd is just a wrapped around boinccmd , all you really need is a way to register your
device with boid.com , i have a separate script just for that purpose in the docker subfolder in this repo called registerdevice.sh , try it out.

Regards,
Gary

**Comment by ghobson2013** [comment]
https://github.com/boid-com/boidcmd/blob/master/docker/register.sh
requires your boid email and password to register your device.
